import Providers from './providers';
import '../public/assets/css/app.css';
import '../public/assets/styles.css';


export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <body className="has-min-sidebar is-header-blur is-sidebar-open">
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
